title: Perplexity Settings
theme: jekyll-theme-minimal
author: Jaakko Korhonen
google_analytics: G-LCTKH734EJ
url: "https://jaakkokorhonen.github.io"
baseurl: "/perplexity-settings"

plugins:
  - jekyll-sitemap

# Exclude source-only files from the Pages build
exclude:
  - cognitive_fallacies.csv
